#Copyright 2018 Goldman Sachs.
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.  
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License.

productGuid: "product::040664"

area:
  producer: "com.gs.marquee"
  package: "gs-quant"
  gns: true
  unpack: false
  artifactDirs:
    - "artifacts"
  gnsRetire:
    policy: "AUTO"
    developmentBuilds: 12
    qaBuilds: 12
    productionBuilds: 12
  deployments:
    - name: gs-quant-deployment
      type: gns
      unpack: true
      properties:
        - "flip.gns.alias.integration=true"
        - "flip.gns.alias.certified=true"
        - "flip.gns.alias.rc=true"
        - "GNSPackage=gs-quant"
      assets:
        - "gs_quant-latest.zip"